version: '3.3'

services:

  db:
    image: postgres:15
    container_name: development_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - development_tracker_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: development_tracker_backend
    depends_on:
      - db
    env_file:
     - .env
    restart: always
    ports:
     - "8000:8000"


volumes:
  development_tracker_volume: