# Generated by Django 4.2.7 on 2023-12-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='skill',
            new_name='skills',
        ),
    ]
