# Generated by Django 4.2.7 on 2023-12-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='selection',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='imageHover',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
