# Generated by Django 4.2.7 on 2023-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
        migrations.AlterModelOptions(
            name='selectionskill',
            options={'verbose_name': 'Скиллы в подборке', 'verbose_name_plural': 'Скиллы в подборке'},
        ),
    ]
