# Generated by Django 4.2.7 on 2023-12-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0003_alter_selectionskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
