# Generated by Django 4.2.7 on 2023-12-07 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0007_alter_selection_image_alter_selection_imagehover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='image',
            field=models.FileField(upload_to='collections/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'csv', 'svg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='imageHover',
            field=models.FileField(upload_to='collections/imageshover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'csv', 'svg'])], verbose_name='Ховер изображение'),
        ),
    ]
