# Generated by Django 4.2.7 on 2023-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы Яндекс Практикум', 'verbose_name_plural': 'Курсы Яндекс Практикума'},
        ),
        migrations.AlterModelOptions(
            name='coursedefaultskill',
            options={'verbose_name': 'Скиллы курса', 'verbose_name_plural': 'Скиллы курса'},
        ),
    ]
