# Generated by Django 4.2.7 on 2023-12-05 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_defaultskill_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursedefaultskill',
            options={'verbose_name': 'Связь курса и навыка', 'verbose_name_plural': 'Связи курсов и навыков'},
        ),
        migrations.AlterModelOptions(
            name='courseuser',
            options={'verbose_name': 'Связь курса и пользователя', 'verbose_name_plural': 'Связи курсов и пользователей'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(through='courses.CourseDefaultSkill', to='skills.defaultskill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(through='courses.CourseUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='coursedefaultskill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursedefaultskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.defaultskill', verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
