# Generated by Django 4.2.7 on 2023-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
