# Generated by Django 4.2.7 on 2023-12-10 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': 'Скиллы пользователя', 'verbose_name_plural': 'Скиллы пользователя'},
        ),
        migrations.AlterField(
            model_name='userskill',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Минимальное значение - 0'), django.core.validators.MaxValueValidator(limit_value=100, message='Максимальное значение - 100')]),
        ),
    ]
