# Generated by Django 4.2.7 on 2023-12-05 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultskill',
            options={'verbose_name': 'Навык по умолчанию', 'verbose_name_plural': 'Навыки по умолчанию'},
        ),
        migrations.AlterModelOptions(
            name='editableskill',
            options={'verbose_name': 'Редактируемый навык', 'verbose_name_plural': 'Редактируемые навыки'},
        ),
        migrations.AlterField(
            model_name='defaultskill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='editableskill',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='editableskill',
            name='notes',
            field=models.CharField(max_length=100, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='editableskill',
            name='rate',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='editableskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
