# Generated by Django 4.2.7 on 2023-12-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultskill',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editableskill',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
