# Generated by Django 4.2.7 on 2023-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Скиллы', 'verbose_name_plural': 'Скиллы'},
        ),
    ]
