# Generated by Django 4.2.7 on 2023-12-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
